### ISSUE TITLE
Add ueberauth_vk support

### ISSUE THREAD

**Issue by sobolevn** [ueberauth/ueberauth_example#33]
Is it a good idea to this provider? https://github.com/sobolevn/ueberauth_vk

I have a concern since it is not widely known outside of Russia. 
Thanks!

**Comment by hassox** [comment]
Does it provide any different information than what is already there about how to set things up? Do you think there's value to adding it?

**Comment by doomspork** [comment]
I think we should refrain from adding third party packages to the example application because:

1) We do not maintain them and don't want to increase the maintenance efforts of this project chasing down maintainers and having them update packages.

2) We have to sign-up for and maintain the apps on the individual providers since this is deployed to Heroku.  Given this one is in Russian, it will be even more difficult to obtain.

We can add links to our README pointing to other example applications.

**Comment by sobolevn** [comment]
Reasonable points! Thanks!
